services:
  backend:
    image: ghcr.io/ohkilab/su-csexpa-benchmark-system-backend:main
    # build:
    #   context: backend
    #   dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - benchmark-service
    volumes:
      - "./backend/storage:/app/storage"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  benchmark-service:
    image: ghcr.io/ohkilab/su-csexpa-benchmark-system-benchmark-service:main
    # build:
    #   context: benchmark-service
    #   dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
  frontend:
    image: ghcr.io/ohkilab/su-csexpa-benchmark-system-frontend:main
    # build:
    #   context: .
    #   dockerfile: frontend/Dockerfile
    environment:
      - NGINX_PORT=80
    depends_on:
      - envoy
      - backend
  envoy:
    # image: ghcr.io/ohkilab/su-csexpa-benchmark-system-envoy:main
    image: envoyproxy/envoy:v1.26-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080 # Backend
      - 80:80 # Frontend
