services:
  backend:
    build:
      context: .
      dockerfile: ./backend/ga.Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - benchmark-service
    volumes:
      - "./backend/storage:/app/storage"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  benchmark-service:
    build:
      context: .
      dockerfile: ./benchmark-service/ga.Dockerfile
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306 # needed for `make seed`
  frontend:
    image: node:20
    working_dir: /proto-gen/web
    volumes:
      - ./frontend:/frontend/:rw
      - ./proto-gen/:/proto-gen/:rw
    command: >
      bash -c "npm i && cd /frontend && npm i -g pnpm && pnpm install && pnpm run dev"
    environment:
      - NGINX_PORT=80
      - OUTER_PORT_FRONTEND=80
      - INNER_PORT_FRONTEND=80
      - HMR_WS_PORT=5000
    depends_on:
      - envoy
      - backend
    ports:
      - 5000:5000 # for Vite Hot Module Reload
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    # network_mode: host
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
      - 80:80
