services:
  backend:
    volumes:
      - type: bind
        source: ./sample-data/v2026/tags
        target: /app/storage/tags/v2026
        read_only: true

  benchmark-service:
    volumes:
      - type: bind
        source: ./benchmark-service/data/v2023.json
        target: /app/data/v2023.json
        read_only: true
      - type: bind
        source: ./sample-data/v2026/v2026.json
        target: /app/data/v2026.json
        read_only: true
